openapi: 3.0.0
info:
  title: My API
  description: This is a simple API for demonstration purposes.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/proofhub13/test-api/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /me:
    get:
      summary: Returns a simple greeting message
      operationId: getGreeting
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: string
                example: Hello
components: {}
