from alembic import op
import sqlalchemy as sa
from models.complete_train import JSONEncodedDict  # 모델에서 JSONEncodedDict을 가져옴

# revision identifiers, used by Alembic.
revision = '337f5a3fa206'
down_revision = '15564a819108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PLAN', 'RUN', 'FIN', name='trainingstatus'), nullable=False))
        batch_op.alter_column('dept_target',
               existing_type=sa.VARCHAR(length=255),
               type_=JSONEncodedDict(),  # 수정된 부분
               existing_nullable=False)
        batch_op.alter_column('role_target',
               existing_type=sa.VARCHAR(length=255),
               type_=JSONEncodedDict(),  # 수정된 부분
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.alter_column('role_target',
               existing_type=JSONEncodedDict(),  # 수정된 부분
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('dept_target',
               existing_type=JSONEncodedDict(),  # 수정된 부분
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
