"""empty message

Revision ID: 41695377a4de
Revises: af9a3bf3e658
Create Date: 2024-09-26 00:27:35.085771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41695377a4de'
down_revision = 'af9a3bf3e658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.drop_column('role_target')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_target', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
