"""empty message

Revision ID: 674baf67abf1
Revises: 
Create Date: 2024-09-29 00:16:41.942527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674baf67abf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code1', sa.String(length=10), nullable=False),
    sa.Column('code2', sa.String(length=50), nullable=False),
    sa.Column('korean_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('korean_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_name', sa.String(length=255), nullable=False),
    sa.Column('training_desc', sa.Text(), nullable=False),
    sa.Column('training_start', sa.DateTime(), nullable=False),
    sa.Column('training_end', sa.DateTime(), nullable=False),
    sa.Column('resource_user', sa.Integer(), nullable=False),
    sa.Column('max_phishing_mail', sa.Integer(), nullable=False),
    sa.Column('dept_target', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complete_trainings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_name', sa.String(length=255), nullable=False),
    sa.Column('training_desc', sa.Text(), nullable=False),
    sa.Column('training_start', sa.DateTime(), nullable=False),
    sa.Column('training_end', sa.DateTime(), nullable=False),
    sa.Column('resource_user', sa.Integer(), nullable=False),
    sa.Column('max_phishing_mail', sa.Integer(), nullable=False),
    sa.Column('dept_target', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PLAN', 'RUN', 'FIN', name='trainingstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_department',
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('training_id', 'department_id')
    )
    op.create_table('complete_training_department',
    sa.Column('complete_training_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['complete_training_id'], ['complete_trainings.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('complete_training_id', 'department_id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('is_phishing', sa.Boolean(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('making_phishing', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('completed_training_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['completed_training_id'], ['complete_trainings.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    op.drop_table('complete_training_department')
    op.drop_table('training_department')
    op.drop_table('event_logs')
    op.drop_table('employees')
    op.drop_table('complete_trainings')
    op.drop_table('trainings')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
