"""empty message

Revision ID: 6e9514db401f
Revises: b1a6f3cfa646
Create Date: 2024-09-11 15:51:29.123274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9514db401f'
down_revision = 'b1a6f3cfa646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.alter_column('dept_target',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('role_target',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.alter_column('role_target',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('dept_target',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
