"""current schema

Revision ID: 847383d96a62
Revises: 
Create Date: 2024-10-05 05:15:08.338587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847383d96a62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('training_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.Column('email_id', sa.Text(), nullable=False),
        sa.Column('event_type', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('data', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )   
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_complete_trainings_training_id', 'trainings', ['training_id'], ['id'])
        batch_op.drop_column('role_target')

    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('email_id')

    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.TEXT(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('department_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_target', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('training_id')

    op.drop_table('user_event_log')


    # ### end Alembic commands ###
