"""empty message

Revision ID: 898466442e99
Revises: 337f5a3fa206
Create Date: 2024-09-17 03:53:20.146764

"""
from alembic import op
import sqlalchemy as sa
from models.complete_train import JSONEncodedDict

# revision identifiers, used by Alembic.
revision = '898466442e99'
down_revision = '337f5a3fa206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.alter_column('dept_target',
               existing_type=sa.TEXT(),
               type_= JSONEncodedDict(),
               existing_nullable=False)
        batch_op.alter_column('role_target',
               existing_type=sa.TEXT(),
               type_=JSONEncodedDict(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complete_trainings', schema=None) as batch_op:
        batch_op.alter_column('role_target',
               existing_type= JSONEncodedDict(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('dept_target',
               existing_type= JSONEncodedDict(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
