"""empty message

Revision ID: 9f4b9360f5fd
Revises: 14015c1514a4
Create Date: 2024-09-12 15:30:29.781343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4b9360f5fd'
down_revision = '14015c1514a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('admin_pw',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('admin_pw',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
