"""rename widget_type to widgetType

Revision ID: a1504f75d394
Revises: e58efccd3e77
Create Date: 2024-09-03 03:41:59.945329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1504f75d394'
down_revision = 'e58efccd3e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widgetType', sa.String(length=50), nullable=False))
        batch_op.drop_column('widget_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('widgetType')

    # ### end Alembic commands ###
