"""empty message

Revision ID: b1a6f3cfa646
Revises: dcf007ad16b3
Create Date: 2024-09-11 14:51:34.541424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a6f3cfa646'
down_revision = 'dcf007ad16b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_trainings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('training_desc', sa.Text(), nullable=False),
    sa.Column('training_start', sa.Date(), nullable=False),
    sa.Column('training_end', sa.Date(), nullable=False),
    sa.Column('resource_user', sa.Integer(), nullable=False),
    sa.Column('max_phishing_mail', sa.Integer(), nullable=False),
    sa.Column('dept_target', sa.String(length=255), nullable=False),
    sa.Column('role_target', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_trainings')
    # ### end Alembic commands ###
