"""empty message

Revision ID: bac7074dd5f5
Revises: 
Create Date: 2024-09-10 23:25:05.049971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac7074dd5f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('emails', schema=None) as batch_op:
        # Temporarily make training_id nullable
        batch_op.add_column(sa.Column('training_id', sa.Integer(), nullable=True))  # Allow NULL for existing records
        batch_op.create_foreign_key('fk_emails_training_id', 'trainings', ['training_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint('fk_emails_training_id', type_='foreignkey')
        batch_op.drop_column('training_id')

    # ### end Alembic commands ###
