"""empty message

Revision ID: c6edf4e29815
Revises: 1c03d0abb620
Create Date: 2024-09-19 01:16:40.733974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6edf4e29815'
down_revision = '1c03d0abb620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('fk_emails_department_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_emails_departments_name', 'departments', ['department_name'], ['name'])
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_emails_departments_name', type_='foreignkey')
        batch_op.create_foreign_key('fk_emails_department_id', 'departments', ['department_id'], ['id'])
        batch_op.drop_column('department_name')

    # ### end Alembic commands ###
