"""empty message

Revision ID: e123e5cc9edc
Revises: bac7074dd5f5
Create Date: 2024-09-11 00:34:59.624380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e123e5cc9edc'
down_revision = 'bac7074dd5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# migrations/versions/[최신 버전 ID]_.py
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('training_id', nullable=True)
        batch_op.alter_column('employee_id', nullable=True)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('training_id', nullable=False, existing_type=sa.Integer())
        batch_op.alter_column('employee_id', nullable=False, existing_type=sa.Integer())

    # ### end Alembic commands ###
